[PKL_STYLE]
firstLine = "//===----------------------------------------------------------------------===//"
endLine = "//===----------------------------------------------------------------------===//"
beforeEachLine = "// "
firstLineDetectionPattern = "//==="
lastLineDetectionPattern = "//==="
